{% set version = "1.3.0" %}

package:
  name: grin
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/g/grin/grin-{{ version }}.tar.gz
  sha256: a8e5a1cc9461322be76cee9bd91fd546d64bbb2fd78dce8acaea9c424ade0db2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - grin = grin:grin_main
    - grind = grin:grind_main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - grin -h
    - grind -h
  imports:
    - grin

about:
  home: http://pypi.python.org/pypi/grin
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Enhanced grep-like tool
  description: |
    Grin is Robert Kern's enhanced grep-like tool analagous to ack(-grep)
    (perl), rak (ruby), and ag (C).
  doc_url: https://pypi.python.org/pypi/grin
  doc_source_url: https://github.com/matthew-brett/grin/blob/master/README.rst
  dev_url: https://github.com/matthew-brett/grin

extra:
  recipe-maintainers:
    - nehaljwani
