{% set version = "1.2.1" %}

package:
  name: grin
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/g/grin/grin-{{ version }}.tar.gz
  sha256: bf39303bc563c4f365365b5ff32e219dc2530a4469b7af25aa6a457ec2e29feb

build:
  number: 1001
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - grin = grin:grin_main
    - grind = grin:grind_main

requirements:
  build:
    - python <3
    - pip 
  run:
    - python <3

test:
  commands:
    - grin -h
    - grind -h
  imports:
    - grin

about:
  home: http://pypi.python.org/pypi/grin
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Enhanced grep-like tool
  description: |
    Grin is Robert Kern's enhanced grep-like tool analagous to ack(-grep)
    (perl), rak (ruby), and ag (C).
  doc_url: https://pypi.python.org/pypi/grin
  doc_source_url: https://github.com/rkern/grin/blob/master/README.rst
  dev_url: https://github.com/rkern/grin

extra:
  recipe-maintainers:
    - nehaljwani
