appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: nYUbxv72fbFE0KA4kNkmk6XtonzVRZhq0w/7hv62BSaAZN4VSWxkQVUDd3ONuM156KA6t3n6pVIR2G1Zk2zz+iWonP6rk8vdSzDLpSfCbyz7M4Ouqoi13fGC/kBUtK5GPCp9+gxONPQ+gZgKwFmcMo8OTroEhvSw/QA/Hs/KXBJyqm3H8q4gOXavJbS0JbUvdm+klwptu1o3AplFF02xX6/CuNbeTBR+hJ5Mtd4BwPijYTqR12nyv/wHznHIZamUr+jVJmbvRRU3kBiGE4imhjaE1yHeeCeUwy2KYl/f9iqBmwtBg8UgQm9NmlcxBMXqX08zye1TtFRJEi4IxOpeS8zgLiu2PdZ2fZp8sE+f8/6TgtKAhJQv+IBtAe+K/rajpW8HReyYzOfRWDztDiumSnaVO5CZJHNCO/ZbKWgFTH0YgJjzr82P1Yv5tyBE4UZ4mXTyw3LME44plfR4lFju+1+1Gonpq6+it3Ty98jsTRB2+wZZo6Es5OEADb4f0GqmcdH302jCXa8jy4zIrepL3llNxo3lJ9sOnyRbDrs7K79QbXLs7bAIvH9oNoa5kjX3zeQDzVI406Y3RE63Ekg8LlJwC1Yz7vhLIgVs5mkAE4Yl8lx/cdyeAbxTJcWHnzkcqAuUel1ANwWsMLnR/isin+TI9rEPZxfvv3OjD2JTgRA=}
conda_forge_output_validation: true
